export default [
  {
    files: [
      "trail/public/**/*.js",
      "scripts/trail_qa.mjs",
      "scripts/management_qa.mjs",
      "scripts/features_qa.mjs",
    ],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: Object.fromEntries(
        [
          "window",
          "document",
          "navigator",
          "location",
          "history",
          "sessionStorage",
          "localStorage",
          "URL",
          "URLSearchParams",
          "fetch",
          "AbortController",
          "AbortSignal",
          "setTimeout",
          "clearTimeout",
          "setInterval",
          "clearInterval",
          "requestAnimationFrame",
          "cancelAnimationFrame",
          "console",
          "process",
          "Event",
          "KeyboardEvent",
          "HTMLElement",
          "HTMLInputElement",
          "Node",
          "performance",
          "getComputedStyle",
          "matchMedia",
        ].map((name) => [name, "readonly"]),
      ),
    },
    rules: {
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "always"],
      "no-constant-condition": "error",
      "no-dupe-args": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-ex-assign": "error",
      "no-fallthrough": "error",
      "no-invalid-regexp": "error",
      "no-loss-of-precision": "error",
      "no-promise-executor-return": "error",
      "no-self-assign": "error",
      "no-sparse-arrays": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-undef": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      "valid-typeof": "error",
    },
  },
];
